<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scrape.Backend\Scrape.Backend.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="TitleScreen.png" />
  </ItemGroup>

</Project>
